// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCwVan4JdjhZBLopFAr5AQ7hkG5i1lxjQ',
    appId: '1:954809297748:web:bbd2fb040d1dd5f87436c1',
    messagingSenderId: '954809297748',
    projectId: 'village-assistance-app',
    authDomain: 'village-assistance-app.firebaseapp.com',
    storageBucket: 'village-assistance-app.firebasestorage.app',
    measurementId: 'G-G18G9LL5XG',
  );

static const FirebaseOptions android = FirebaseOptions(
  apiKey: 'AIzaSyDt5WpTDa5mwxjAEpzIkdpQ9Y-Bkfm4Y2Q',
  appId: '1:942480274228:android:21e924a6bb959233ae2b61',
  messagingSenderId: '942480274228',
  projectId: 'sats-disaster-sih',
  storageBucket: 'sats-disaster-sih.firebasestorage.app',
);
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsoW7VrUfINJUmXF4PVA2BuO-5G0frFzg',
    appId: '1:954809297748:ios:420e3485f15168fc7436c1',
    messagingSenderId: '954809297748',
    projectId: 'village-assistance-app',
    storageBucket: 'village-assistance-app.firebasestorage.app',
    iosClientId: '954809297748-rm0j5g4a3firpj9sqsh0fer7gjm5f4ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.villageVerse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsoW7VrUfINJUmXF4PVA2BuO-5G0frFzg',
    appId: '1:954809297748:ios:420e3485f15168fc7436c1',
    messagingSenderId: '954809297748',
    projectId: 'village-assistance-app',
    storageBucket: 'village-assistance-app.firebasestorage.app',
    iosClientId: '954809297748-rm0j5g4a3firpj9sqsh0fer7gjm5f4ce.apps.googleusercontent.com',
    iosBundleId: 'com.example.villageVerse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-e26C7_rSA3nJdOBa5oPG7S6ijAIPdL0',
    appId: '1:942480274228:web:e529491824ed3db1ae2b61',
    messagingSenderId: '942480274228',
    projectId: 'sats-disaster-sih',
    authDomain: 'sats-disaster-sih.firebaseapp.com',
    storageBucket: 'sats-disaster-sih.firebasestorage.app',
    measurementId: 'G-THYJBYDL05',
  );
}
